//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemsOrder()
        {
            this.ItemInOrder = new HashSet<ItemInOrder>();
        }
    
        public Nullable<decimal> TotalSum { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int ItemsOrderId { get; set; }
        public int SupplierId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> StoreId { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemInOrder> ItemInOrder { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Store Store { get; set; }
    }
}
