//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Sale = new HashSet<Sale>();
            this.ItemInStore = new HashSet<ItemInStore>();
            this.ItemInOrder = new HashSet<ItemInOrder>();
        }
    
        public int ItemId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> AnimalId { get; set; }
        public string Description { get; set; }
        public Nullable<int> ItemSubcategoryId { get; set; }
        public string Volume { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemInStore> ItemInStore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemInOrder> ItemInOrder { get; set; }
        public virtual ItemSubcategory ItemSubcategory { get; set; }
        public Sale GetCurrentSale()
        {
            return this.Sale.Where(s => (s.StartDate > DateTime.UtcNow) && (s.EndDate < DateTime.UtcNow)).FirstOrDefault();
        }
    }
}
